// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddNode: typeof import('./src/components/addNode.vue')['default']
    ApproverDrawer: typeof import('./src/components/drawer/approverDrawer.vue')['default']
    ConditionDrawer: typeof import('./src/components/drawer/conditionDrawer.vue')['default']
    CopyerDrawer: typeof import('./src/components/drawer/copyerDrawer.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    EmployeesDialog: typeof import('./src/components/dialog/employeesDialog.vue')['default']
    EmployeesRoleDialog: typeof import('./src/components/dialog/employeesRoleDialog.vue')['default']
    ErrorDialog: typeof import('./src/components/dialog/errorDialog.vue')['default']
    NodeWrap: typeof import('./src/components/nodeWrap.vue')['default']
    PromoterDrawer: typeof import('./src/components/drawer/promoterDrawer.vue')['default']
    RoleDialog: typeof import('./src/components/dialog/roleDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectBox: typeof import('./src/components/selectBox.vue')['default']
    SelectResult: typeof import('./src/components/selectResult.vue')['default']
  }
}
